[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
EasyHybrid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
YAXArrays = {rev = "main", url = "https://github.com/JuliaDataCubes/YAXArrays.jl"}
