[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
EasyHybrid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
